### ISSUE TITLE
Handling type conversion errors in mutation handlers

### ISSUE THREAD

**Issue by josemanuelp** [andogq/qubit#69]
### Description

When there is a conversion error, the thread panics, and there is no way to handle the error or notify the client that the error occurred because of the panic.

In my case, I have a mutation handler that converts a string to an IPv4 address:

```rust
#[handler(mutation)]
async fn add_connection(_dbctx: DbCtx, ip_address: Ipv4AddrDB, port: u16) -> Result<(), AppError> {
```

However, when the client sends an invalid address, it generates the following panic:

```
thread 'tokio-runtime-worker' panicked at src/ui_rpc/rpc.rs:50:1:
called `Result::unwrap()` on an `Err` value: ErrorObject { code: InvalidParams, message:
"Invalid params", data: Some(RawValue("invalid IPv4 address syntax at line 1 column 5"))
}
```

### Question

Is there any way to handle type conversion errors in handlers? Alternatively, do you know of a recommended way of dealing with such cases?

Thanks!

**Comment by andogq** [comment]
I've just made a few tweaks, let me know how they suit your problem.

Now if an error occurs whilst deserialising the parameters, it will be returned down to the client like so:

```jsonc
{
  code: -32602,
  message: 'Invalid params',
  data: 'invalid type: string "asdf", expected u32 at line 1 column 7' // This will be the deserialisation error message
}
```

You'll have to `catch` the handler to actually receive it in JS (`my_api.handler.query(...).catch((e) => ...)`).

An alternate approach for your circumstance would be to have the handler accept a `String` as the `ip_address` parameter, and parse it in your handler. This would let you return a custom `AppError`, rather than just relying on the error from Serde.

One final approach would be to make your own wrapper struct for some type, and implement `Deserialize` manually, so that you can define your own error message if it gets presented to the user.

Let me know if any of these approaches work, or if there's a better API/example of an API that you would prefer.
